//REACT_APP_SEPOLIA_RPC_URL=
//REACT_APP_ETHEREUM_RPC_URL=
//REACT_APP_WALLETCONNECT_PROJECT_ID=
// REACT_APP_INFURA_PROJECT_ID=
// PRIVATE_KEY=
// REACT_APP_CA_TRUMP=
//SUPABASE_URL=
//SUPABASE_SERVICE_ROLE_KEY=